// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TouchBase.Data;

#nullable disable

namespace TouchBase.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220420183333_AddedReference")]
    partial class AddedReference
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TouchBase.Model.ProjectCollectionModel", b =>
                {
                    b.Property<int>("ProjectCollectionModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectCollectionModelId"), 1L, 1);

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectCollectionModelId");

                    b.ToTable("ProjectCollection", (string)null);

                    b.HasData(
                        new
                        {
                            ProjectCollectionModelId = 1,
                            CompanyName = "Great Lakes Cloud Solutions, LLC"
                        });
                });

            modelBuilder.Entity("TouchBase.Model.ProjectModel", b =>
                {
                    b.Property<int>("ProjectModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectModelId"), 1L, 1);

                    b.Property<string>("Approximation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDone")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectCollectionModelId")
                        .HasColumnType("int");

                    b.HasKey("ProjectModelId");

                    b.HasIndex("ProjectCollectionModelId");

                    b.ToTable("Project", (string)null);

                    b.HasData(
                        new
                        {
                            ProjectModelId = 1,
                            Approximation = "Your Mom",
                            Description = "Stuff and things",
                            IsDone = false,
                            Name = "First Model",
                            ProjectCollectionModelId = 1
                        });
                });

            modelBuilder.Entity("TouchBase.Model.ProjectModel", b =>
                {
                    b.HasOne("TouchBase.Model.ProjectCollectionModel", "ProjectCollectionModel")
                        .WithMany("ProjectModels")
                        .HasForeignKey("ProjectCollectionModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectCollectionModel");
                });

            modelBuilder.Entity("TouchBase.Model.ProjectCollectionModel", b =>
                {
                    b.Navigation("ProjectModels");
                });
#pragma warning restore 612, 618
        }
    }
}
